"""Shared enum constants for the final SRS message contract."""

CSI_STATUS = {"AVAILABLE", "UNAVAILABLE", "STUB"}
RISK_LEVELS = {"LOW", "MEDIUM", "HIGH"}
RECOMMENDED_ACTIONS = {"NO_ACTION", "OBSERVE", "VERIFY_USER", "NOTIFY_GUARDIAN"}
USER_RESPONSES = {"NOT_ASKED", "OK", "NOT_OK", "HELP", "NO_RESPONSE", "UNCLEAR"}
RESPONSE_OUTCOMES = {
    "NORMAL_CLOSED",
    "OBSERVING",
    "VERIFIED_OK_CLOSED",
    "ESCALATED_TO_GUARDIAN",
    "NOTIFICATION_FAILED",
}
NOTIFICATION_STATUSES = {"NOT_REQUIRED", "SENT", "FAILED"}
ANALYSIS_STATUSES = {"SUCCESS", "FALLBACK_RULE", "FAILED"}
VERIFICATION_METHODS = {"NONE", "LOCAL_MP3_STT"}

DEFAULT_PROMPT_ASSET = "are_you_ok_ko.mp3"
DEFAULT_EXPECTED_OK_TEXT = ["네"]
HELP_KEYWORDS = ["도와줘", "살려줘", "119", "구해줘", "응급", "응급실", "위험"]
NOT_OK_KEYWORDS = ["아파", "못 일어나", "못일어나", "아니", "아니요", "괜찮지 않아", "안 괜찮"]
